{{-- Modal: Eliminar documento definitivamente --}}

<div
    id="document-permanent-delete-modal"
    class="
        hidden
        fixed
        inset-0
        z-50
        bg-black/60
        items-center
        justify-center
        p-4
    "
>
    <div
        class="
            relative
            w-full
            max-w-md
            rounded-2xl
            bg-white
            dark:bg-[#020817]
            border
            border-slate-200
            dark:border-slate-800
            shadow-2xl
            overflow-hidden
        "
    >
        {{-- HEADER --}}
        <div
            class="
                flex
                items-center
                justify-between
                px-6
                py-5
                border-b
                border-slate-200
                dark:border-slate-800
            "
        >
            <div>
                <h2
                    class="
                        text-xl
                        font-bold
                        text-red-600
                        dark:text-red-400
                    "
                >
                    Eliminar definitivamente
                </h2>
                <p
                    class="
                        mt-1
                        text-sm
                        text-slate-500
                        dark:text-slate-400
                    "
                >
                    Esta acción no se puede deshacer.
                </p>
            </div>
            <button
                type="button"
                id="close-document-permanent-delete-modal"
                class="
                    w-9
                    h-9
                    rounded-xl
                    flex
                    items-center
                    justify-center
                    text-slate-500
                    dark:text-slate-400
                    hover:bg-slate-100
                    dark:hover:bg-slate-800
                    transition
                "
            >
                <img
                    src="{{ asset('images/documentacion/salir.png') }}"
                    alt="Cerrar"
                    class="w-5 h-5 object-contain"
                >
            </button>
        </div>
        {{-- CONTENIDO --}}
        <div class="px-6 py-6">

            <div
                class="
                    flex
                    items-center
                    gap-4
                    rounded-xl
                    bg-red-50
                    dark:bg-red-950/20
                    border
                    border-red-200
                    dark:border-red-900/50
                    p-4
                "
            >
                {{-- ICONO --}}
                <div
                    class="
                        w-12
                        h-12
                        rounded-xl
                        bg-white
                        dark:bg-slate-800
                        border
                        border-slate-200
                        dark:border-slate-700
                        flex
                        items-center
                        justify-center
                        flex-shrink-0
                        overflow-hidden
                    "
                >
                    <img
                        id="permanent-delete-document-file-icon"
                        src=""
                        alt="Icono del archivo"
                        class="
                            w-full
                            h-full
                            object-contain
                            p-2
                        "
                    >
                </div>
                {{-- INFORMACIÓN --}}
                <div class="min-w-0">
                    <p
                        id="permanent-delete-document-name"
                        class="
                            text-sm
                            font-bold
                            text-slate-700
                            dark:text-slate-200
                            truncate
                        "
                    >
                        -
                    </p>
                    <p
                        id="permanent-delete-document-file-name"
                        class="
                            mt-1
                            text-xs
                            text-slate-500
                            dark:text-slate-400
                            truncate
                        "
                    >
                        -
                    </p>
                </div>
            </div>
            <div
                class="
                    mt-5
                    rounded-xl
                    bg-red-50
                    dark:bg-red-950/20
                    border
                    border-red-200
                    dark:border-red-900/50
                    px-4
                    py-3
                "
            >
                <p
                    class="
                        text-sm
                        font-semibold
                        text-red-700
                        dark:text-red-400
                    "
                >
                    ⚠️ Atención
                </p>
                <p
                    class="
                        mt-1
                        text-xs
                        text-red-600
                        dark:text-red-400
                    "
                >
                    El archivo físico será eliminado permanentemente.
                    Esta acción no podrá deshacerse.
                </p>
            </div>
        </div>

        {{-- FOOTER --}}
        <div
            class="
                flex
                items-center
                justify-end
                gap-3
                px-6
                py-4
                border-t
                border-slate-200
                dark:border-slate-800
                bg-slate-50
                dark:bg-slate-900/40
            "
        >
            <button
                type="button"
                id="cancel-document-permanent-delete-modal"
                class="
                    px-5
                    py-2.5
                    rounded-xl
                    bg-slate-200
                    hover:bg-slate-300
                    dark:bg-slate-800
                    dark:hover:bg-slate-700
                    text-slate-700
                    dark:text-slate-200
                    font-semibold
                    transition
                "
            >
                Cancelar
            </button>
            <form
                id="document-permanent-delete-form"
                method="POST"
            >
                @csrf
                @method('DELETE')

                <button
                    type="submit"
                    class="
                        px-5
                        py-2.5
                        rounded-xl
                        bg-red-600
                        hover:bg-red-700
                        text-white
                        font-semibold
                        transition
                    "
                >
                    🗑️ Eliminar definitivamente
                </button>
            </form>
        </div>
    </div>
</div>